/*
    Tests for the BQL generated by the Quick Query builder. Expected queries
    are asserted exactly: they are the contract with the ledger engine.
    (quickQuery.integration.test.ts checks they actually execute.)
*/
import { describe, expect, it } from 'vitest';
import {
	buildAssertQuery,
	buildBalanceQuery,
	buildLotsQuery,
	buildPriceQuery,
	buildQuery,
	buildRegisterQuery,
	type CommonOptions,
	type LotsOptions
} from '$lib/services/quickQueryBuilder';

const common = (overrides: Partial<CommonOptions> = {}): CommonOptions => ({
	account: [],
	currency: [],
	total: false,
	hierarchy: false,
	zero: false,
	closedAccounts: false,
	...overrides
});

const lots = (overrides: Partial<LotsOptions> = {}): LotsOptions => ({
	account: [],
	currency: [],
	average: false,
	active: true,
	showAll: false,
	closed: false,
	...overrides
});

describe('buildBalanceQuery', () => {
	it('excludes closed accounts by default', () => {
		expect(buildBalanceQuery(common())).toBe(
			'SELECT account, units(sum(position)) as Balance WHERE NOT close_date(account) GROUP BY account ORDER BY account ASC'
		);
	});

	it('includes closed accounts when requested', () => {
		expect(buildBalanceQuery(common({ closedAccounts: true }))).toBe(
			'SELECT account, units(sum(position)) as Balance GROUP BY account ORDER BY account ASC'
		);
	});

	it('filters by account regex, ANDed together', () => {
		const query = buildBalanceQuery(common({ account: ['Assets', 'Bank'] }));

		expect(query).toContain(
			"WHERE account ~ 'Assets' AND account ~ 'Bank' AND NOT close_date(account)"
		);
	});

	it('supports exclusions with not', () => {
		const query = buildBalanceQuery(common({ account: ['Expenses', 'not', 'Rent', 'Dining'] }));

		expect(query).toContain(
			"account ~ 'Expenses' AND NOT (account ~ 'Rent') AND NOT (account ~ 'Dining')"
		);
	});

	it('ends an exclusion list at the next @ or not keyword', () => {
		const query = buildBalanceQuery(common({ account: ['not', 'Rent', '@shop', 'Assets'] }));

		expect(query).toContain("description ~ 'shop'");
		expect(query).toContain("NOT (account ~ 'Rent')");
		expect(query).toContain("account ~ 'Assets'");
		expect(query).not.toContain("NOT (account ~ 'shop')");
	});

	it('supports @ payee/description filters', () => {
		expect(buildBalanceQuery(common({ account: ['@Supermarket'] }))).toContain(
			"description ~ 'Supermarket'"
		);
	});

	it('handles a single and multiple currencies, normalised to upper case', () => {
		expect(buildBalanceQuery(common({ currency: ['eur'] }))).toContain("currency = 'EUR'");
		expect(buildBalanceQuery(common({ currency: ['eur, usd', 'aud'] }))).toContain(
			"currency IN ('EUR', 'USD', 'AUD')"
		);
	});

	it('ignores empty currency entries', () => {
		expect(buildBalanceQuery(common({ currency: [' , '] }))).not.toContain('currency');
	});

	it('adds a converted column for --exchange', () => {
		const query = buildBalanceQuery(common({ exchange: 'eur' }));

		expect(query).toContain("convert(sum(position), 'EUR') as Converted");
	});

	it('honours sort and limit', () => {
		const query = buildBalanceQuery(common({ sort: '-account,date', limit: 10 }));

		expect(query.endsWith('ORDER BY account DESC, date ASC LIMIT 10')).toBe(true);
	});

	it('emits LIMIT 0 rather than dropping a zero limit', () => {
		expect(buildBalanceQuery(common({ limit: 0 }))).toContain('LIMIT 0');
	});
});

describe('date handling', () => {
	const query = (opts: Partial<CommonOptions>) => buildRegisterQuery(common(opts));

	it('expands partial dates for begin/end', () => {
		expect(query({ begin: '2025' })).toContain('date >= 2025-01-01');
		expect(query({ begin: '2025-3' })).toContain('date >= 2025-03-01');
		expect(query({ end: '2025-08-15' })).toContain('date < 2025-08-15');
	});

	it('expands a year range to the whole year', () => {
		expect(query({ dateRange: '2025' })).toContain('date >= 2025-01-01 AND date < 2026-01-01');
	});

	it('expands a month range, including the December rollover', () => {
		expect(query({ dateRange: '2025-08' })).toContain('date >= 2025-08-01 AND date < 2025-09-01');
		expect(query({ dateRange: '2025-12' })).toContain('date >= 2025-12-01 AND date < 2026-01-01');
	});

	it('expands a single day to that day', () => {
		expect(query({ dateRange: '2025-08-31' })).toContain(
			'date >= 2025-08-31 AND date < 2025-09-01'
		);
		expect(query({ dateRange: '2025-12-31' })).toContain(
			'date >= 2025-12-31 AND date < 2026-01-01'
		);
	});

	it('supports open and closed explicit ranges', () => {
		expect(query({ dateRange: '2025-01..2025-06' })).toContain(
			'date >= 2025-01-01 AND date < 2025-06-01'
		);
		expect(query({ dateRange: '2025-01..' })).toContain('date >= 2025-01-01');
		expect(query({ dateRange: '2025-01..' })).not.toContain('date <');
		expect(query({ dateRange: '..2025-06' })).toContain('date < 2025-06-01');
		expect(query({ dateRange: '..2025-06' })).not.toContain('date >=');
	});

	it('ignores unparseable dates instead of emitting bad BQL', () => {
		expect(query({ begin: 'soon', dateRange: 'later' })).not.toContain('WHERE');
	});
});

describe('buildRegisterQuery', () => {
	it('has no WHERE or ORDER BY without options', () => {
		expect(buildRegisterQuery(common())).toBe('SELECT date, account, payee, narration, position');
	});

	it('combines filters, conversion, sort and limit', () => {
		const query = buildRegisterQuery(
			common({ account: ['Expenses'], currency: ['EUR'], exchange: 'usd', sort: '-date', limit: 5 })
		);

		expect(query).toBe(
			"SELECT date, account, payee, narration, position, convert(position, 'USD') as Converted WHERE account ~ 'Expenses' AND currency = 'EUR' ORDER BY date DESC LIMIT 5"
		);
	});
});

describe('buildAssertQuery', () => {
	it('reads from #balances and filters on amount.currency', () => {
		expect(buildAssertQuery(common({ account: ['Bank'], currency: ['eur'] }))).toBe(
			"SELECT date, account, amount FROM #balances WHERE account ~ 'Bank' AND amount.currency = 'EUR'"
		);
	});

	it('uses IN for several currencies', () => {
		expect(buildAssertQuery(common({ currency: ['eur', 'usd'] }))).toContain(
			"amount.currency IN ('EUR', 'USD')"
		);
	});
});

describe('buildPriceQuery', () => {
	it('defaults to date then currency ordering', () => {
		expect(buildPriceQuery(common())).toBe(
			'SELECT date, currency, amount FROM #prices ORDER BY date ASC, currency ASC'
		);
	});

	it('treats account tokens as commodity filters, ORed', () => {
		expect(buildPriceQuery(common({ account: ['vti'] }))).toContain("WHERE currency ~ 'VTI'");
		expect(buildPriceQuery(common({ account: ['vti', 'bnd'] }))).toContain(
			"WHERE (currency ~ 'VTI' OR currency ~ 'BND')"
		);
	});

	it('applies dates, sort and limit', () => {
		expect(buildPriceQuery(common({ begin: '2025-01', sort: '-date', limit: 3 }))).toBe(
			'SELECT date, currency, amount FROM #prices WHERE date >= 2025-01-01 ORDER BY date DESC LIMIT 3'
		);
	});
});

describe('buildLotsQuery', () => {
	it('defaults to active lots grouped by cost basis', () => {
		const query = buildLotsQuery(lots());

		expect(query).toContain('WHERE cost_number IS NOT NULL');
		expect(query).toContain(
			'GROUP BY account, currency(units(position)), cost_number, cost_currency HAVING SUM(number(units(position))) > 0'
		);
		expect(query.endsWith('ORDER BY date ASC')).toBe(true);
	});

	it('closed lots have no remaining units', () => {
		expect(buildLotsQuery(lots({ active: false, closed: true }))).toContain(
			'HAVING SUM(number(units(position))) <= 0'
		);
	});

	it('--all lists individual positions without grouping', () => {
		const query = buildLotsQuery(lots({ active: false, showAll: true }));

		expect(query).not.toContain('GROUP BY');
		expect(query).not.toContain('HAVING');
		expect(query).toContain('SELECT date, account,');
	});

	it('average groups per account and symbol', () => {
		const query = buildLotsQuery(lots({ average: true }));

		expect(query).toContain(
			'GROUP BY account, currency(units(position)) HAVING SUM(number(units(position))) > 0'
		);
		expect(query).toContain('total_weighted_cost');
	});

	it('adds converted value for --exchange in every mode', () => {
		for (const opts of [
			lots({ exchange: 'eur' }),
			lots({ exchange: 'eur', average: true }),
			lots({ exchange: 'eur', active: false, closed: true }),
			lots({ exchange: 'eur', active: false, showAll: true })
		]) {
			expect(buildLotsQuery(opts)).toContain("'EUR') as converted_value");
		}
	});

	it('sorts by --sort, else --sort-by, else date', () => {
		expect(buildLotsQuery(lots({ sort: '-price', sortBy: 'symbol' }))).toContain(
			'ORDER BY price DESC'
		);
		expect(buildLotsQuery(lots({ sortBy: 'symbol' }))).toContain('ORDER BY symbol ASC');
		expect(buildLotsQuery(lots())).toContain('ORDER BY date ASC');
	});

	it('sorts average lots by avg_price when sorting by price', () => {
		expect(buildLotsQuery(lots({ average: true, sortBy: 'price' }))).toContain(
			'ORDER BY avg_price ASC'
		);
	});

	it('applies currency filters and limit', () => {
		const query = buildLotsQuery(lots({ currency: ['vti', 'bnd'], limit: 2 }));

		expect(query).toContain("currency IN ('VTI', 'BND')");
		expect(query.endsWith('LIMIT 2')).toBe(true);
	});
});

// TODO: the builder interpolates user text straight into '...' BQL literals (account/@payee
// patterns, currencies, exchange), so a single quote breaks the query. Harmless (own data,
// own device) but should be escaped or rejected; then replace this with real tests.
describe('quoting of user input', () => {
	it.todo('escapes or rejects a single quote in an account pattern, e.g. "Joe\'s"');
	it.todo('escapes or rejects a single quote in an @payee filter');
});

describe('buildQuery', () => {
	it('dispatches to the right builder per command', () => {
		const c = common();
		const l = lots();

		expect(buildQuery('balance', c, l)).toBe(buildBalanceQuery(c));
		expect(buildQuery('register', c, l)).toBe(buildRegisterQuery(c));
		expect(buildQuery('lots', c, l)).toBe(buildLotsQuery(l));
		expect(buildQuery('assert', c, l)).toBe(buildAssertQuery(c));
		expect(buildQuery('price', c, l)).toBe(buildPriceQuery(c));
	});
});
